CREATE USER IF NOT EXISTS 'abssystem'@'localhost' IDENTIFIED BY 'system';
CREATE DATABASE IF NOT EXISTS abssystem;
USE abssystem;

CREATE TABLE IF NOT EXISTS `PARAMETERS` (
    `ID`              BIGINT        NOT NULL AUTO_INCREMENT,
    `NAME`            VARCHAR( 200) NOT NULL,
    `VALUE_NUMBER`    DOUBLE,
    `VALUE_CHAR`      VARCHAR(1000),
    `VALUE_DECIMAL`   DECIMAL,
PRIMARY KEY(ID)
);

TRUNCATE TABLE `PARAMETERS`;

INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('BATTLESHIP.MAX_SIZE'           ,   400);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('MAP.MAX_WIDTH'                 ,   150);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('MAP.MAX_HEIGHT'                ,   150);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('SUBSYSTEM.DISTANCE_FROM_HULL'  ,     1);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('SUBSYSTEM.DISTANCE_FROM_OTHERS',     5);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_DECIMAL`) VALUES('GAME.AVAILABLE_MONEY'          ,  2500);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('GAME.MINES_COUNT'              ,     5);

GRANT ALL PRIVILEGES ON `abssystem`.* TO 'abssystem'@'localhost';