CREATE USER IF NOT EXISTS 'abssystem'@'localhost' IDENTIFIED BY 'system';
CREATE DATABASE IF NOT EXISTS abssystem;
USE abssystem;

CREATE TABLE IF NOT EXISTS `PARAMETERS` (
    `ID`              BIGINT        NOT NULL AUTO_INCREMENT,
    `NAME`            VARCHAR( 200) NOT NULL,
    `VALUE_NUMBER`    DOUBLE,
    `VALUE_CHAR`      VARCHAR(1000),
    `VALUE_DECIMAL`   DECIMAL,
PRIMARY KEY(ID)
);

TRUNCATE TABLE `PARAMETERS`;

INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('BATTLESHIP.MAX_SIZE'                       ,   400);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('BATTLESHIP.MIN_LENGTH_SIZE'                ,     3);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_DECIMAL`) VALUES('BATTLESHIP.HULL_CELL_COST'                 ,     1);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('MAP.MAX_WIDTH'                             ,   150);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('MAP.MAX_HEIGHT'                            ,   150);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('SUBSYSTEM.DISTANCE_FROM_HULL'              ,     1);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('SUBSYSTEM.DISTANCE_FROM_OTHERS'            ,     5);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_DECIMAL`) VALUES('GAME.AVAILABLE_MONEY'                      ,  2500);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('GAME.MINES_COUNT'                          ,     5);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('SECURITY.SESSION_PING_SECS'                ,    20);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('SECURITY.SESSION_CHECK_SECS'               ,    60);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('SECURITY.EXPECTED_ONLINE_USER_COUNT'       ,  2000);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('MESSAGES.NOTIFICATIONS_POLLING_INTERVAL_MS',  5000);
INSERT INTO `PARAMETERS`(`NAME`, `VALUE_NUMBER` ) VALUES('MESSAGES.MAX_NOTIFICATIONS_ON_SCREEN'      ,     5);

GRANT ALL PRIVILEGES ON `abssystem`.* TO 'abssystem'@'localhost';