CREATE USER IF NOT EXISTS 'absmessaging'@'localhost' IDENTIFIED BY 'messaging';
CREATE DATABASE IF NOT EXISTS absmessaging;
USE absmessaging;

CREATE TABLE IF NOT EXISTS `PERSISTENT_MESSAGE_SOURCE_TYPE` (
    `ID`              BIGINT        NOT NULL AUTO_INCREMENT,
    `NAME`            VARCHAR( 200) UNIQUE NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE IF NOT EXISTS `PERSISTENT_MESSAGE_TYPE` (
    `ID`              BIGINT        NOT NULL AUTO_INCREMENT,
    `NAME`            VARCHAR( 200) UNIQUE NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS `PERSISTENT_MESSAGE_CHANNEL` ( 
    `ID`              BIGINT        NOT NULL AUTO_INCREMENT,
    `NAME`            VARCHAR( 200) UNIQUE NOT NULL,
    `MESSAGE_TYPE_ID` BIGINT        NOT NULL REFERENCES `PERSISTENT_MESSAGE_TYPE`(`ID`),
PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS `PERSISTENT_MESSAGE` (
    `ID`                  BIGINT        NOT NULL AUTO_INCREMENT,
    `CHANNEL_ID`          BIGINT        NOT NULL REFERENCES `PERSISTENT_MESSAGE_CHANNEL`(`ID`),
    `USER_UNIQUE_TOKEN`   CHAR   (  12) BINARY UNIQUE NOT NULL,
    `SOURCE_UNIQUE_TOKEN` CHAR   (  12) BINARY UNIQUE NOT NULL,
    `SOURCE_TYPE_ID`      BIGINT        NOT NULL REFERENCES `PERSISTENT_MESSAGE_SOURCE_TYPE`(`ID`),
    `MESSAGE_TIME`        TIMESTAMP     NOT NULL,
    `TITLE`               VARCHAR( 200) NOT NULL,
    `BODY`                VARCHAR(2000),
    `IS_IMPORTANT`        BOOLEAN       NOT NULL DEFAULT FALSE,
    `IS_READ`             BOOLEAN       NOT NULL DEFAULT FALSE,
PRIMARY KEY(ID)
);


INSERT INTO `PERSISTENT_MESSAGE_TYPE`(`NAME`) VALUES
	('friend request'),
	('party request'),
	('game invitation'),
	('system message'),
	('news')
;

INSERT INTO `PERSISTENT_MESSAGE_CHANNEL`(`NAME`, `MESSAGE_TYPE_ID`)
	          SELECT 'friend requests' , (SELECT MAX(`ID`) FROM `PERSISTENT_MESSAGE_TYPE` WHERE `NAME` = 'friend request')
	UNION ALL SELECT 'party requests'  , (SELECT MAX(`ID`) FROM `PERSISTENT_MESSAGE_TYPE` WHERE `NAME` = 'party request')
	UNION ALL SELECT 'game invitaitons', (SELECT MAX(`ID`) FROM `PERSISTENT_MESSAGE_TYPE` WHERE `NAME` = 'game invitation')
	UNION ALL SELECT 'system messages' , (SELECT MAX(`ID`) FROM `PERSISTENT_MESSAGE_TYPE` WHERE `NAME` = 'system message')
	UNION ALL SELECT 'global news'     , (SELECT MAX(`ID`) FROM `PERSISTENT_MESSAGE_TYPE` WHERE `NAME` = 'news')
;

COMMIT;

GRANT ALL PRIVILEGES ON `absmessaging`.* TO 'absmessaging'@'localhost';